// a2/src/react-site/src/App.tsx
import { useEffect, useState } from "react";
import "./App.css";
import axios from "axios";

function App() {
  type Task = {
    done: boolean;
    id: number;
    name: string;
  };

  const [tasks, setTasks] = useState<Task[]>([]);
  const [newTaskName, setNewTaskName] = useState<string>('');
  const api_url = "http://127.0.0.1:5000/api/items/";

  useEffect(() => {
    getTasks();
  }, []);

  const getTasks = async () => {
    const result = await axios.get(api_url);
    setTasks(result.data["items"]);
  };

  const deleteAllTasks = () => {
    const requests = tasks.map((task) => axios.delete(`${api_url}${task.id}`));

    axios
      .all(requests)
      .then(getTasks)
      .catch((error) => console.log(error.request.response));
  };

  const deleteTask = (id: number) => {
    console.log("deleting task", id);
    axios
      .delete(`${api_url}${id}`)
      .then(getTasks)
      .catch((error) => console.log(error.request.response));
  };

  const completeTask = (id: number) => {
    console.log("completing task", id);

    const task = tasks.find((t) => t.id === id);
    let updatedTask = { ...task };
    updatedTask.done = !updatedTask.done;
    axios
      .put(`${api_url}${id}`, updatedTask)
      .then(getTasks)
      .catch((error) => console.log(error.request.response));
  };

  const updateTaskName = (id: number, event: any) => {
    const newValue = event.target.value;
    const task = tasks.find((t) => t.id === id);

    if (task) {
      task.name = newValue;
      axios
        .put(`${api_url}${id}`, task)
        .then(getTasks)
        .catch((error) => console.log(error.request.response));
    }
  };

  const appendTask = () => {
    const newTask = {
      name: newTaskName,
    };
    
    axios
      .post(api_url, newTask)
      .then(getTasks)
      .catch((error) => console.log(error.request.response));
  };

  const taskList = tasks?.map((task, idx) => (
    <div key={idx} style={{ display: "flex" }}>
      <input
        defaultValue={task.name}
        onBlur={(event) => updateTaskName(task.id, event)}
      />
      <button onClick={() => deleteTask(task.id)}>Delete task</button>
      <button onClick={() => completeTask(task.id)}>Complete task</button>
      {task.done ? "completed" : "not completed"}
    </div>
  ));

  const newTaskInput = (
    <form onSubmit={appendTask}>
      <input placeholder={"new task"} value={newTaskName} onChange={(e) => setNewTaskName(e.target.value)}/>
      <input type="submit" value="Submit" />
    </form>
  );

  return (
    <div className="App">
      <h1>TODO INF-2300</h1>
      {newTaskInput}
      <button onClick={deleteAllTasks}>Delete all tasks</button>
      {taskList}
    </div>
  );
}

export default App;

// a2/src/site/src/App.vue

<template>
  <div class="parent">
    <head style="display: flex; padding-bottom: 40px;">
      <h1>TODO INF-2300</h1>    
      <input type="button" value="Delete all" @click="deleteAllTasks">
    </head>
    <div class="new">
      <input v-model="newTaskName" placeholder="New task" size="50">
      <input type="button" value="+" @click="appendTask">
    </div>
      <ul>
        <li v-for="task in tasks" class="todoitem">
          <input v-model="task.name" :class="{completedTask: task.done}" size="50" @change="updateTaskName(task.id)">
          <input type="button" value="&#10004" class="button" style="background-color:rgb(142, 211, 142)" @click="completeTask(task.id)">
          <input type="button" value="&#10006" class="button" style="background-color:rgb(221, 33, 33)" @click="deleteTask(task.id)">
        </li>
      </ul>
  </div>
</template>

<script setup lang="ts">
import { onMounted, ref } from 'vue';
import axios from 'axios'

type Task = {
  "done": boolean,
  "id": number,
  "name": string,
};

const api_url = "http://127.0.0.1:5000/api/items/"
const tasks = ref<Task[]>([]);
const newTaskName = ref('')

const getTasks = () => axios.get(api_url)
  .then(response => tasks.value = response.data["items"])
  .catch(error => alertError(error.request.response));

onMounted(getTasks);

const alertError = (error: string) => {
  const parsedError = JSON.parse(error);
  alert(`${parsedError.Message}: ${parsedError.Code}\n${parsedError.Description}`)
}

const deleteTask = (id: number) => {
  axios.delete(`${api_url}${id}`)
    .then(getTasks)
    .catch(error => alertError(error.request.response));
}


const completeTask = (id: number) => {
  const task = tasks.value.find(t => t.id === id);
  let updatedTask = { ...task };
  if (updatedTask) {
    updatedTask.done = !updatedTask.done;
    axios.put(`${api_url}${id}`, updatedTask)
      .then(getTasks)
      .catch(error => alertError(error.request.response))
  } else {
    alertError('No task with that id was found');
  }
}

const updateTaskName = (id: number) => {
  let task = tasks.value.find(t => t.id === id);

  axios.put(`${api_url}${id}`, task)
    .then(getTasks)
    .catch(error => alertError(error.request.response));
}

const deleteAllTasks = () => {
  const requests = tasks.value.map(task => axios.delete(`${api_url}${task.id}`));

  axios.all(requests)
    .then(getTasks)
    .catch(error => alertError(error.request.response));
}

const appendTask = () => {
  const newTask = {
    "name": newTaskName.value,
  }

  axios.post(api_url, newTask)
    .then(getTasks)
    .catch(error => alertError(error.request.response));

  newTaskName.value = '';
};
</script>


<style scoped>
.parent {
  text-align: center;
}

.new {
  padding-right: 2.5em;
}

h1 {
  margin: 0 auto;
}

ul, li {
  list-style: none;
  padding-left: 0;
  padding-top: 5px;
}
.completedTask {
  background-color: rgb(142, 211, 142);
}

input, button {
  font-size: inherit;
  padding: 0.3em 0.4em;
  margin: 0.1em 0.2em;
  background-color: #fff;
}
</style>
